project:
  type: website
  output-dir: docs
website:
  title: "gunkholesailing.com"
  favicon: gunkholescene.jpg
  sidebar:
    title: "Captain's Logs"
    logo: Outlierlogo.png
    background: secondary
    style: floating
    contents: Gunkhole Adventures
  navbar:
    logo: Outlierlogo.png
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Outlier"
        menu: 
          - outlier.qmd
          - motor.qmd
          - outlier_dinghy.qmd
     
      - text: "Gunkhole Seamanship"
        menu:
          - seamanship.qmd
          - navigation.qmd
          - weather.qmd
          - mooring.qmd
      - videos.qmd
      - text: "Bluewater Dreaming"
        menu: 
          - boats.qmd
          - dinghies.qmd  
format:
  html:
    theme:  lumen # zephyr, yeti, superhero, sketchy, lumen, materia, sandstone
    css: styles.css
    toc: true


