---
title: "Gunkhole Seamanship"
---

**Gunkhole seamanship** is a term I created to describe the type of sailing I do.

* small, often trailerable sailboat
* shoal draft
* protected waters such as lakes and rivers.
* desire for solitude
* secret spots that are difficult to get to and have no ammenities.
* single-handed or short-handed sailing due to limited vessel capacity.

These characteristics often require specialized techniques that are not discussed in much of the traditional sailing literature.
Most books on seamanship related sailing focus on boat th

>"To be forehanded is to be cautious and even pessimistic. A forehanded sailor looks ahead, anticipates the worst, and prepares for it by, among other things, setting and observing standard operating procedures."  
                        - John Rousmanere[^1]
  
The title of this section is much more of an aspiration than assertion.
The goal of this section is to document my journey to try to become a good sailor.

The initial purpose of the whole  site is as a repository for the information to document what I have done to become a sailor, and to help me plan future projects and adventures.
I hope it might also be helpful to others.

[^1]: Rousmaniere, J. (1999). *The Annapolis Book of Seamanship: Completely Revised, Expanded and Updated*. Simon and Schuster.