---
title: "Captain's Log 2023"
---


### Lake Martin (Young's Island and Dare Park), March 24-25

I had planned two nights on the lake. I got to the marina early Friday evening, splashed, rigged, and stocked *Outlier* and was planning on staying at the dock that night. Insetad, I decided to go out and watch the sunset, maybe returning, maybe staying out at anchor. Eventually, I decided to stay out and sailed over to Wood's Island looking at the small cove on the southeast of the island just behind the beach area. The trees protecting this cove from a southern wind seemed too little for adequate protection, so I made my way across to Young's Island. I left the Mantis II anchor sitting on the foredeck, and not surprisingly, it fell into the water on the way over. I turned into the wind, recovered the anchor, which, forehandedly, I did secure the other end of the rode to the boat, then continued over to the cove on the southwestern side of Young's Island.

 I expected rain early Saturday morning -- predictions were for about 6am. I was anchored in the big cove on the southeast part of Young's Island, which is protected from the north east and south, but no the east. The winds were predicted to be from the south/southeast all weekend. Early Saturday morning a fairly strong storm blew in and the wind clocked from south to directly east. I realized this, when after closing the v-berth hatch about 4am due to light rain, just before 6am I was awakened by outlier swinging 180 degrees in about 3 seconds. Now instead of being a out 150 feet off shore I was about 40 feet from a lee shore, with winds increasing. the 180 degrees swing meant the anchor was likely to reset, and I had little room for that to happen. I put on my "foulies" (i.e. my rain jacket. I've got to get some more rain pants), and waited in the companion way only able to see the shore during lightning flashes for the first 10-20 minutes of the squall. Of course my anus was very puckered during this time: if I did start dragging, I would have to jump out and hope the outboard would crank, AND be able to push Outlier with the tarp up (windage) against 20-25 knot winds. Turns out the Mantis II held like a tank. Best money I've spent on this boat. And it was in there. I had to back the boat of the anchor in the other direction. I couldn't dislodge it by hand. My only regret: I didn't film it. What?! I've got to start filming these things.
All and all, I learned lot's and feel this year each time I go out several things start to "click".